# 使用輕量級的 nginx 映像檔
FROM --platform=linux/x86-64 nginx:alpine

# 拷貝靜態文件到 nginx 預設的 web 目錄
COPY dist/website_editor /var/www/html/tnt-ssr-engine
# 拷貝自訂的 Nginx 配置文件
COPY nginx.conf /etc/nginx/conf.d/default.conf
# 暴露 nginx 預設的 80 埠
EXPOSE 80

# 啟動 nginx
CMD ["nginx", "-g", "daemon off;"]




# docker build -t yihsuehlin/kp-vue3-enigma:latest -f Dockerfile .
# docker run -d -p 8080:80 yihsuehlin/kp-vue3-enigma